### ISSUE TITLE
Model as input to ACGD Optimizer rather than parameters

### ISSUE THREAD

**Issue by jshanna100** [devzhk/Implicit-Competitive-Regularization#10]
Is there a reason why the ACGD Optimizer takes entire models as input rather than Parameter lists? This is different from general Pytorch optimizer usage, as well as the other CGD optimizers. This makes usage inconvenient where the Discriminator/Generator are made of more than one network.

**Comment by devzhk** [comment]
Oh, good point! Technically there is no difficulty to make ACGD's input as same as general optimizer's. I'm planning to update this. Thanks for your advice.

**Comment by zr-bee** [comment]
> 
May I ask, has this point been realized?

**Comment by zr-bee** [comment]
> Oh, good point! Technically there is no difficulty to make ACGD's input as same as general optimizer's. I'm planning to update this. Thanks for your advice.

Has it been realized now? Brothers

**Comment by devzhk** [comment]
Yes, the code has been updated. Please checkout this CGDs packages https://github.com/devzhk/cgds-package if you are interested.

**Comment by zr-bee** [comment]
hey, Thanks.&nbsp; If my generator is assembled from two networks, if using this ddp? How to use this acgd? Can you help me with my doubts? thank you very much.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devzhk/Implicit-Competitive-Regularization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 凌晨0:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devzhk/Implicit-Competitive-Regularization] Model as input to ACGD Optimizer rather than parameters (#10)





 
Yes, the code has been updated. Please checkout this CGDs packages https://github.com/devzhk/cgds-package if you are interested.

**Comment by devzhk** [comment]
You can just wrap them into one nn.Module. 
Not sure what you mean by using this ddp. Do you mean using acgd with Pytorch DistributedDataParallel?

**Comment by zr-bee** [comment]
Yes, I just want to use its distribution--&nbsp;using acgd with Pytorch DistributedDataParallel;

what’s the meaning？Is it the second type?

or
？







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月26日(星期三) 下午2:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [devzhk/Implicit-Competitive-Regularization] Model as input to ACGD Optimizer rather than parameters (#10)





 
You can just wrap them into one nn.Module.
 Not sure what you mean by using this ddp. Do you mean using acgd with Pytorch DistributedDataParallel?

**Comment by devzhk** [comment]
Sorry, I don't understand your question. If you want to use ACGD with Pytorch DDP, please see the instructions in the README of https://github.com/devzhk/cgds-package.

**Comment by zr-bee** [comment]
I use GAN for training and generating tasks, and my generator has two networks for training and a discriminator;The first question is, I don't know how to use ACGD;The second question, I don't know how to use Pytorch's DDP for distributed training, because the link seems to be a generator for a single network.发自我的手机-------- 原始邮件 --------发件人： devzhk ***@***.***>日期： 2023年4月26日周三 下午2:29收件人： devzhk/Implicit-Competitive-Regularization ***@***.***>抄送： lr-lpl ***@***.***>, Comment ***@***.***>主    题： Re: [devzhk/Implicit-Competitive-Regularization] Model as input to ACGD Optimizer rather than parameters (#10)
Sorry, I don't understand your question. If you want use ACGD with Pytorch DDP, please see the instructions in the README of https://github.com/devzhk/cgds-package.

**Comment by devzhk** [comment]
You can always wrap two networks into one torch.nn.Module. 
For example, 
```python
class MetaModel(torch.nn.Module):
    def __init__(net1, net2):
          self.net1 = net1
          self.net2 = net2
    
    def forward(net1_input, net2_input):
          out1 = net1(net1_input)
          out2 = net2(net2_input)
          return out1, out2
```

ACGD can accept this MetaModel. In principle, you can always wrap all the networks with the same optimization direction into one MetaModel and feed it to the optimizer.

**Comment by zr-bee** [comment]
I would like to ask, have you encountered this problem before? thank you very much.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devzhk/Implicit-Competitive-Regularization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 凌晨1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devzhk/Implicit-Competitive-Regularization] Model as input to ACGD Optimizer rather than parameters (#10)





 
You can always wrap two networks into one torch.nn.Module.
 For example,
 class MetaModel(torch.nn.Module):     def __init__(net1, net2):           self.net1 = net1           self.net2 = net2          def forward(net1_input, net2_input):           out1 = net1(net1_input)           out2 = net2(net2_input)           return out1, out2
 
ACGD can accept this MetaModel. In principle, you can always wrap all the networks with the same optimization direction into one MetaModel and feed it to the optimizer.

**Comment by devzhk** [comment]
Do you mean the problem where you have two generators? Nope, I haven't but it should be straightforward to get around.

**Comment by zr-bee** [comment]
question：



It should be defined that there is no problem with the step operation that can be run in the cgd optimizer? But the above error will always be reported. I need the help of my brother very much. I hope that my brother can help me solve the problem.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devzhk/Implicit-Competitive-Regularization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月28日(星期五) 凌晨2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devzhk/Implicit-Competitive-Regularization] Model as input to ACGD Optimizer rather than parameters (#10)





 
Do you mean the problem where you have two generators? Nope, I haven't but it should be straightforward to get around.

**Comment by zr-bee** [comment]
Here is the training code




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devzhk/Implicit-Competitive-Regularization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月28日(星期五) 凌晨2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devzhk/Implicit-Competitive-Regularization] Model as input to ACGD Optimizer rather than parameters (#10)





 
Do you mean the problem where you have two generators? Nope, I haven't but it should be straightforward to get around.

**Comment by devzhk** [comment]
I can't see any code or error in your message. They are not displayed in your comment.

**Comment by zr-bee** [comment]
Sorroy. It's my fault.I re-upload the relevant code in the attachment.
The error:

&nbsp;
I hope you help me. Bro


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devzhk/Implicit-Competitive-Regularization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月5日(星期五) 凌晨0:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devzhk/Implicit-Competitive-Regularization] Model as input to ACGD Optimizer rather than parameters (#10)





 
I can't see any code or error. They are not displayed.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

function.py (15.4K, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=79323032bbf69dc9705f524b1634501941460951070d5a041404080b0319535709031d03510c071b000b09020052530f58560654303f62504c5c5346595b0c18494b300f&t=exs_ftn_download&code=920204b6




seg_hrnet.py (36.1K, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=74626535415cc8cf7c0f074c1233051f4d165357575001071852560d561e0e04065648045052551d075254025150550507525257343f374350053a5d465d52441b121c3509&t=exs_ftn_download&code=5be54370




train.py (15.9K, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0b61656352f2c6cc7f0c071a1e320b1c4e15525b590058041b045505091f0a04045348020d535d1e0f03535b5e010e5707585755383a394744000c0d164240330b&t=exs_ftn_download&code=6aec8293

**Comment by devzhk** [comment]
Hi, would it be possible for you to share the code directly on Github issue? This way, it can be displayed in the comment and it would be much easier for me to read and follow along this issue.
